protocol: 'https:'
host: 'e.ueda.tech'
sitetitle: 'Ryuichi Ueda and CIT Autonomous Robot Lab'
subtitle: ''
headline:
- text: '<a href="https://b.ueda.tech">Personal site in Japanese</a>'
- text: '<a href="https://lab.ueda.tech">Lab site in Japanese</a>'
twitter:
- account: 'uedarobotics'
facebook: '@'
hatena: '@'
pocket: '@'
line: '@'
links:
- text: 'latest'
  href: '/?post'
- text: 'publications'
  href: '/?page=publication_en'
- text: 'projects'
  sublinks:
  - text: 'opy'
    href: 'https://github.com/ryuichiueda/opy'
  - text: 'GlueLang'
    href: '/?page=GlueLang'
  - text: 'Team ARAIBO'
    href: 'http://www.araibo.com'
- text: 'Japanese'
  sublinks:
  - text: 'Personal page'
    href: 'https://b.ueda.tech'
  - text: 'Laboratory'
    href: 'https://lab.ueda.tech'
sociallinks:
- icon: 'fa-wikipedia-w'
  href: 'https://ja.wikipedia.org/wiki/%E4%B8%8A%E7%94%B0%E9%9A%86%E4%B8%80'
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/uedarobotics'
- icon: 'fa-github-square'
  href: 'https://github.com/ryuichiueda'
- icon: 'fa-slideshare'
  href: 'https://www.slideshare.net/ryuichiueda'
- icon: 'fa-facebook-squar'
  href: 'https://www.facebook.com/%E4%B8%8A%E7%94%B0-%E9%9A%86%E4%B8%80-675930229170437/'
- icon: 'fa-linkedin-square'
  href: 'https://www.linkedin.com/in/%E9%9A%86%E4%B8%80-%E4%B8%8A%E7%94%B0-81391649'
- icon: 'fa-instagram'
  href: 'https://www.instagram.com/ryuichiueda/'
- icon: 'fa-graduation-cap'
  href: 'https://www.researchgate.net/profile/Ryuichi_Ueda'
- icon: 'fa-question'
  href: 'https://peing.net/ja/ryuichiueda'
